# Generated by Django 2.0.4 on 2018-04-06 08:01

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'Phone number should have country code (for mobiles) and Country + Area code for home phone number. For Instance: +61 412 123 456 OR +61294152222'}, max_length=128, null=True),
        ),
    ]
